acqusitions_labels = ['AAHead_Scout',
                      'AAHead_Scout_MPR_sag',
                      'AAHead_Scout_MPR_cor',
                      'AAHead_Scout_MPR_tra',
                      'PhoenixZIPReport',
                      't2w4radiology',
                      't1_mprage_short',
                      'StartFMRI',
                      'intermediate t-Map',
                      'Design',
                      'Student work',
                      'EvaSeries_GLM',
                      'Mean_&_t-Maps',
                      'StartFMRI',
                      'Pedagogy',
                      'StartFMRI',
                      'intermediate t-Map',
                      'Design',
                      'Pedagogy',
                      'EvaSeries_GLM',
                      'Mean_&_t-Maps',
                      'StartFMRI',
                      'intermediate t-Map',
                      'Design',
                      'Pedagogy',
                      'EvaSeries_GLM',
                      'Mean_&_t-Maps',
                      'StartFMRI',
                      'intermediate t-Map',
                      'Design',
                      'Student feedback']

acquistions_object = [{'label': a} for a in acqusitions_labels]